name: Update KernelSU-Next Submodule

on:
  workflow_dispatch:

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update KernelSU-Next
        run: |
          git submodule update --init --remote KernelSU-Next

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add KernelSU-Next
          git commit -m "KSUN: update to latest next-susfs" || echo "No changes"
          git push